### ISSUE TITLE
From for Kernel

### ISSUE THREAD

**Issue by andreysobol** [pandoraboxchain/pyrrha-webclient#1]
Create web form for kernel

**Comment by dr-orlovsky** [comment]
Kernel constructor arguments are explained in comments in https://github.com/pandoraboxchain/pyrrha-consensus/blob/master/contracts/entities/Kernel.sol

Dataset constructor arguments are explained in comments in
https://github.com/pandoraboxchain/pyrrha-consensus/blob/master/contracts/entities/Dataset.sol

**Comment by dr-orlovsky** [comment]
Kernel IPFS main information file consists of two required strings:
1) Keras model file (JSON);
2) neural network weights file (HDF5 format).

a minimalistic sample of the main kernel JSON file is the following:
```
{
  "model": "QmPhtLgduZaCJFQ4SReNMDnHo7Lb6YyVQU1wCiJdvw6CJa", // IPFS address for Keras JSON model
  "weights": "QmQuHbEaQem2KGHwgpcZs7dHMeu8sm4npjbDA8NRXLPfPo", // IPFS address for HDF5 weights file
}
```

This file must be constructed in the Web browser, so basically UI must provide two file fields (for model and weights), upload those files to IPFS, put resulting addresses into JSON structure (shown above) and upload it as a file to IPFS – specifying the resulting address as the first argument to the constructor.

Additionally UI must ask for data dimension, complexity and price — three `uint` fields, which must be provided by the kernel author hands directly in the UI and later be used as the rest of the arguments for the constructor.

**Comment by dr-orlovsky** [comment]
Dataset IPFS main information file consists of the array listing IPFS addresses for each of the batches in the HDF5 format:

```
{
  "batches": [
    "QmNxi5m9oZekHcfddayPwKNmsFfBGAP39CZXSnjnC2yF6B",
    // ...
  ]
}
```

So UI must provide an array of N fields to upload each batch file, add it to IPFS, construct JSON from the addresses and upload it to IPFS, presenting the resulting address as a first argument to the Dataset constructor, together with the total count of the batches also given to the constructor.

The rest of constructor arguments (price, samples count, data dimension) must be provided by the dataset owner in hands (via appropriate input fields in the UI)

**Comment by dr-orlovsky** [comment]
Instead of uploading large HDF5 files to IPFS in the browser we can simply ask a user to upload them himself outside of the browser and just provide resulting IPFS addresses as strings in UI form.

**Comment by kostysh** [comment]
version 1.2.3 has been published. 
but in this version, an only regular way of kernel uploading has been implemented.
Do we still need this simplified way now (without uploading of files)?
Maybe we will create this form later?
