### ISSUE TITLE
Form for Cognitive Job

### ISSUE THREAD

**Issue by andreysobol** [pandoraboxchain/pyrrha-webclient#3]
Create web form for Cognitive Job

**Comment by kostysh** [comment]
The current version of the Webclient already has job creation form. But, creation process seems not working with currently published contracts (rinkeby network)

**Comment by kostysh** [comment]
Job creation form working as expected. But UI should be improved. 

Before the job creation started we should to:
- check a count of available worker nodes
- check dataset maximum  batches count
- validate dataset and kernel to be matched by data dimension
